# Generated by Django 3.1 on 2022-02-16 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220216_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4125678e-1de1-46af-b333-909064bb7b60'), editable=False, primary_key=True, serialize=False),
        ),
    ]
